### ISSUE TITLE
File in use

### ISSUE THREAD

**Issue by rvanrosmalen** [wpoely86/redmine-azure-devops-migrate#7]
Hi,

Using Python 3 on my Windows 10 system I installed the requirements plus python-certifi-win32 because I got certificate validation errors without it. Those are gone but now I get:

Traceback (most recent call last):
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\importlib\_common.py", line 89, in _tempfile
    os.write(fd, reader())
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\importlib\abc.py", line 371, in read_bytes
    with self.open('rb') as strm:
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\importlib\_adapters.py", line 54, in open
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rro\AzureDevops\redmine-azure-devops-migrate\migrate.py", line 16, in <module>
    from redminelib import Redmine
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\redminelib\__init__.py", line 14, in <module>
    from . import managers, exceptions, engines, utilities, resources
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\redminelib\engines\__init__.py", line 6, in <module>
    from .sync import SyncEngine
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\redminelib\engines\sync.py", line 5, in <module>
    import requests
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py", line 133, in <module>
    from . import utils
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 27, in <module>
    from . import certs
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\wrapt\importer.py", line 170, in exec_module
    notify_module_loaded(module)
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\wrapt\decorators.py", line 470, in _synchronized
    return wrapped(*args, **kwargs)
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\wrapt\importer.py", line 136, in notify_module_loaded
    hook(module)
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\certifi_win32\wrapt_certifi.py", line 20, in apply_patches
    certifi_win32.wincerts.CERTIFI_PEM = certifi.where()
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\site-packages\certifi\core.py", line 37, in where
    _CACERT_PATH = str(_CACERT_CTX.__enter__())
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\rro\AppData\Local\Programs\Python\Python310\lib\importlib\_common.py", line 95, in _tempfile
    os.remove(raw_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rro\\AppData\\Local\\Temp\\tmp12y7rd3y'

Any ideas how to fix this one?

**Comment by wpoely86** [comment]
I'm afraid not. It already trips over `from redminelib import Redmine` so that points to a problem in your python installation itself.

I have no experience with running Python under a windows environment. These scripts were written with Python 3.8. I think they should just work fine with 3.10 but it's not tested.

The last error seems to indicate that some other python processes might already be started? It's trying and failing to remove a temporarily file.

**Comment by rvanrosmalen** [comment]
On what platform/distro can I best run this? Linux? With ubuntu I also got the CERTIFICATE_VERIFY_FAILED issues and failed to fix it yet

**Comment by rvanrosmalen** [comment]
Got it working on Windows 10 with Python 3.8.10 and the certifi-win32 pip package
